Question:1
Create a 2D NumPy array with dimensions 5x5. Replace all elements in the last column with the mean value of that column.

In [4]:
import numpy as np
array_2d=np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25],
])
mean = np.mean(array_2d, axis=0)

array_2d_mean=np.full(array_2d.shape,mean)
print(array_2d_mean)             

[[11. 12. 13. 14. 15.]
 [11. 12. 13. 14. 15.]
 [11. 12. 13. 14. 15.]
 [11. 12. 13. 14. 15.]
 [11. 12. 13. 14. 15.]]


Question 2:
Create a 3x3 identity matrix

In [6]:
array=np.ones((3,3))
array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
array[1][2]=7
array

array([[1., 1., 1.],
       [1., 1., 7.],
       [1., 1., 1.]])

In [10]:
array[1][1]


1.0

In [11]:
np.linspace(1,500,5)

array([  1.  , 125.75, 250.5 , 375.25, 500.  ])

Question:3
Consider a (8,7) shape array, what is the index (x,y) of the 35th element?

In [12]:
def find_index(element_index,rows,columns):
    x=element_index//columns
    y=element_index%columns
    return(x,y)

element_index=35
rows=8
columns=7
index= find_index(element_index, rows, columns)
print(f" the index of the {element_index}th element is:{index}")

 the index of the 35th element is:(5, 0)


In [14]:
a=np.linspace(2,200,100).reshape((10,10))
a

array([[  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.],
       [ 22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.],
       [ 42.,  44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.],
       [ 62.,  64.,  66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.],
       [ 82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,  98., 100.],
       [102., 104., 106., 108., 110., 112., 114., 116., 118., 120.],
       [122., 124., 126., 128., 130., 132., 134., 136., 138., 140.],
       [142., 144., 146., 148., 150., 152., 154., 156., 158., 160.],
       [162., 164., 166., 168., 170., 172., 174., 176., 178., 180.],
       [182., 184., 186., 188., 190., 192., 194., 196., 198., 200.]])

In [15]:
a.sum(axis=0).argmax()

9

In [16]:
np.diag((1,2,3,4,5))


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

Question 4:
Create a NumPy array with the numbers 1 to 100. Reshape it into a 10x10 array. Calculate the sum of each row and find the row with the maximum sum.(Hint: you can use 'np.random.randint' to create the 2d array and fill it with random numbers

In [24]:
array=np.arange(1,101)

array_reshaped=array.reshape(10,10)

row_sum=array_reshaped.sum(axis=1)

max_sum_row_index=np.argmax(row_sum)

print("Array")

print(array_reshaped)
print()
print(row_sum)
print()
print(max_sum_row_index)

Array
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

[ 55 155 255 355 455 555 655 755 855 955]

9
